return {
  "nvim-treesitter/nvim-treesitter",
  event = "LazyFile",
  opts = {
    ensure_installed = {
      "astro",
      "bash",
      "css",
      "dockerfile",
      "fish",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "html",
      "htmldjango",
      "json5",
      "just",
      "lua",
      "markdown",
      "markdown_inline",
      "ninja",
      "python",
      "regex",
      "ron",
      "rst",
      "rust",
      "svelte",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    },
  },
}
